rrt_stanley:
  ros__parameters:
    waypoints_path: "/home/f1tenth/f1tenth_ws_waterloo/track/FTM_big_track/big_track_raceline_mincurv.csv"
    waypoints_path_2nd: "/home/f1tenth/f1tenth_ws_waterloo/track/FTM_big_track/big_track_raceline_mincurv.csv"
    scan_topic: "/scan"
    odom_topic: "/pf/pose/odom"
    drive_topic: "/drive"
    interpolation_distance: 0.05
    #velocity_percentage: 0.8      # default: 0.8
    lane_number: 0

    #K_p: 10                      # default: 0.5 
    #K_p_obstacle: 0.8
    #K_E: 1.0
    #K_H: 0.5

    #min_lookahead: 1.5 # for larger track                                     default: 1.5
    #max_lookahead: 2.5 # lookahead when the car is going around max velocity  default: 2.5
    #min_lookahead_speed: 0.5 
    #max_lookahead_speed: 1.0 # approximately the max velocity

    # For when there is an obstacle
    #velocity_min: 0.5      # default: 0.5
    #velocity_max: 1.5      # deffault: 1.0
    #steering_limit: 25.0   # default: 25
    cells_per_meter: 10    # default: 20
    
waypoint_visualizer_node:
  ros__parameters:
    waypoints_path: "/home/f1tenth/f1tenth_ws_waterloo/track/FTM_big_track/big_track_raceline_mincurv.csv"
